# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: notifier

# ---------------------------
# Logging & Tracking
# ---------------------------

logger:
  dir: logger

# ---------------------------------------
# Example of User Section
# ---------------------------------------

training:
  lr: 0.5