# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: email-notification

# ---------------------------
# Logging & Tracking
# ---------------------------

logger:
  dir: logger

# ---------------------------------------
# Email Notification Settings
# ---------------------------------------

notification:
  subject: "Training Update from fenn"
  
# ---------------------------------------
# Training Configuration
# ---------------------------------------

train:
    lr: 0.001
    epochs: 10